version: "3.8"

services:

  postgresql:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "network-db"
      POSTGRES_USER: "network-db"
      POSTGRES_PASSWORD: "network-db"
    ports:
      - "7432:5432"
    volumes:
      - ./init.db/init.sql:/docker-entrypoint-initdb.d/init.sql

