version: "3.8"

services:

  network-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8081"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/network-db

  postgresql:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "network-db"
      POSTGRES_USER: "network-db"
      POSTGRES_PASSWORD: "network-db"
    ports:
      - "7432:5432"
    volumes:
      - ./init.db/init.sql:/docker-entrypoint-initdb.d/init.sql
