server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:7432/network-db
    username: network-db
    password: network-db
    driver-class-name: org.postgresql.Driver

jwt:
  secret: "GMeCgNRWgLR6RlzQJ5RPsN59SK44dHys0Vu2MwkEmxw="


logging:
  level:
    root: DEBUG
